repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
      args: ["--config=.flake8", "--exclude=tests/html_coding.py"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
    - id: mypy
      args: ["--config-file", "mypy.ini", "--strict"]
      exclude: tests/*|setup.py
