dist: xenial
language: python
cache: apt

before_install:
  - sudo apt update

install:
  # Install IDOM along with test requirements
  - pip install -r requirements.txt
  - pip install .

script: cd $WORK_DIR && eval $TEST_CMD

matrix:
  include:
    - name: "python-3.6"
      python: 3.6
      env:
        - WORK_DIR="."
        - TEST_CMD="bash scripts/test.sh"
    - name: "python-3.7"
      python: 3.7
      env:
        - WORK_DIR="."
        - TEST_CMD="bash scripts/test.sh"
